### ISSUE TITLE
♻️ 알림 도메인과 타 도메인간의 강한 결합 개선

### ISSUE THREAD

**Issue by JiHongKim98** [100-hours-a-week/5-Joytas-dao-be#302]
### ♻️ 진행할 작업 설명

현재 알림 도메인 이벤트는 특정 도메인 이벤트 `LoungeInvitedEvent`, `ObjetInviteEvent` 등과 강하게 결합되어 있어
타 도메인의 이벤트 식별자가 변경되면 알림 도메인도 함께 변경되는 부수적인 문제가 발생하고 있다.
따라서, 도메인간의 결합을 느슨하게 가져가 유지보수성을 높이기 위해 이벤트 식별자(identify) 기반 리팩토링 진행

### ☘️TODO

- [x] 알림 도메인에서 타 도메인에 대한 의존성 제거
- [x] 도메인 컨버터 클래스 제거
- [x] 전역으로 이벤트를 관리했던 `DomainEvent` 제거 및 개별 관리로 수정
