### ISSUE TITLE
♻️ Redis Pub/Sub 로직 리팩토링

### ISSUE THREAD

**Issue by JiHongKim98** [100-hours-a-week/5-Joytas-dao-be#312]
### ♻️ 진행할 작업 설명

Redis PUB/SUB 로직을 간편하게 사용하기 위해서 만든 [Redis-Extensions](https://github.com/JiHongKim98/redis-extensions) 라이브러리 적용

### ☘️TODO

- [x] `Redis Extentions` 라이브러리 의존성 추가
- [x] 알림 PUB/SUB 로직 수정
- [ ] 채팅 PUB/SUB 로직 수정
