### ISSUE TITLE
♻️ Data Source 설정 고도화

### ISSUE THREAD

**Issue by JiHongKim98** [100-hours-a-week/5-Joytas-dao-be#313]
### ♻️ 진행할 작업 설명

스프링 애플리케이션 실행시 `엔티티의 레포지토리에 대해 식별할 수 없다` 라는 메시지가 엔티티의 개수만큼 발생하던 문제 해결

![image](https://github.com/user-attachments/assets/871ffb09-a71c-4037-87a7-324b16def424)

### ☘️TODO

- [x] JPA 패키지 스캔 범위 설정 추가
- [x] MongoDB 패키지 스캔 범위 설정 추가
- [x] Redis Repository 설정 삭제
